server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # 配置Git仓库的地址
          uri: https://github.com/2YSP/spring-cloud-config-repo.git
          # 配置Git仓库的用户名
          username: 2YSP
          # 配置Git仓库的密码
          password: xxx
