
spring:
  application:
    name: microservice-discovery-eureka-ha
---
############### 指定profile=peer1
spring:
  profiles: peer1

server:
  port: 8761
eureka:
  instance:
  ## 当profile=peer1时,hostname=peer1
    hostname: peer1
  client:
    ### 将自己注册到peer2这个Eureka上
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
---
############### 指定profile=peer2
spring:
  profiles: peer2

server:
  port: 8762
eureka:
  instance:
    ## 当profile=peer2时,hostname=peer2
    hostname: peer2
  client:
    ### 将自己注册到peer1这个Eureka上
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

