spring:
  application:
    name: service-b
  zipkin:
    base-url: http://localhost:9411
  # 抽样收集的百分比，默认10%
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9002